### ISSUE TITLE
For the newsletter, the disabled symbol have to come when we hover over the submit arrow without filling the input.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#15]
**Actual result:**
For the newsletter, the disabled symbol have to come when we hover over the submit arrow without filling the input.
![image](https://user-images.githubusercontent.com/102131636/170181909-e9bbdf77-b748-4d76-a87c-985ef38ceafa.png)

**Expected result:**
The disabled symbol have to come when we hover over the submit arrow. As we have used a disabled symbol for all the input fields

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved,

we have used red colour for the error message but it is looking very bad.
