### ISSUE TITLE
The content is missing for the Billings terms and conditions and Shipping policy.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#17]
**The url :**
https://www.studio1995co.com/pages/shipping-policy
https://www.studio1995co.com/pages/billing-terms-conditions
**Actual result:**
The content is missing for the Billings terms and conditions and Shipping policy.
**Expected result:**
The content must be added

**Comment by devSuneel** [comment]
the client has not provided the content

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
