### ISSUE TITLE
For the social media links in the footer the linking is not given.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#20]
**Actual result:**
For the social media links in the footer the linking is not given.( For all link linking is not given  )
![image](https://user-images.githubusercontent.com/102131636/170184414-66b3a302-2acd-45f2-a50e-c118c869fcb6.png)
![image](https://user-images.githubusercontent.com/102131636/170184431-2eb58fc6-b64b-4756-8d12-36aeeae55caf.png)

**Expected result:**
The linking have to be provided for all the social media links

**Comment by devSuneel** [comment]
not provided by the client

**Comment by sudhanshu0603** [comment]
ok ,resolved
