### ISSUE TITLE
The same linking is given for the 2 buttons.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#22]
**The url:**
https://www.studio1995co.com/products/studio1995%E2%84%A2-photography-background-kit

**Actual result:**
The same linking is given for the 2 buttons in home page
![image](https://user-images.githubusercontent.com/102131636/170185778-7f3986fb-627b-443e-a419-e32612928e03.png)
![image](https://user-images.githubusercontent.com/102131636/170185799-d927dd72-8336-4860-bfb6-01672c340350.png)

**Expected result:**
We can give the different product link for both the buttons.

**Comment by devSuneel** [comment]
added link same as live site

**Comment by sudhanshu0603** [comment]
ok, resolved
