### ISSUE TITLE
The banners are not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#23]
**Actual result:**
The banners are not clickable.
![image](https://user-images.githubusercontent.com/102131636/170186127-6074531b-2260-4aac-9793-63a7c84c46c3.png)
![image](https://user-images.githubusercontent.com/102131636/170186174-a515ec43-d370-441e-90f1-08bd99767610.png)

**Expected result:**
The banners have to be clickable.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
