### ISSUE TITLE
in home page when we click on the youtube button then error message is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#24]
**Actual result:**
in home page when we click on the youtube button then error message is coming.
![image](https://user-images.githubusercontent.com/102131636/170186443-6bb7bc1b-786c-49b5-9e5c-f27df786b035.png)
![image](https://user-images.githubusercontent.com/102131636/170186461-d1217c7d-0116-4018-ad86-0c7e579fad53.png)

**Expected result:**
The youtube video have to be play.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
The cross symbol is coming behind it can be improved.
![image](https://user-images.githubusercontent.com/102131636/170452436-28ba8fea-ed9b-47da-8189-53c333e54944.png)
@ui-neelu

**Comment by sudhanshu0603** [comment]
ok resolved
