### ISSUE TITLE
In product page, the product may also like, the quick view is not coming on hover.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#30]
**The url:**
https://www.studio1995co.com/products/t-shape-metal-backdrop-background-stand-frame-support-multiple-sizes-for-photography-photo-studio-video-cromakey-green-screen?variant=42757883592939
**Actual result:**
In product page, the product may also like, the quick view is not coming on hover.
![image](https://user-images.githubusercontent.com/102131636/170191697-01006d8a-a3f2-4ae1-9dcd-589167808296.png)

**Expected result:**
The quick view button have to be added for section you may also like

**Comment by devSuneel** [comment]
resolved
