### ISSUE TITLE
In cart page, the main added product image is not clickable.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#31]
**Actual result:**
In cart page, the main added product image is not clickable.
![image](https://user-images.githubusercontent.com/102131636/170192217-32790ce4-fb08-4b59-8dba-66d7b293bd76.png)

**Expected result:**
The main image have to be clickable and opens the product page related to it.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
hand cursor is coming below the main image.

**Comment by sudhanshu0603** [comment]
as discuss we can ignore it
