### ISSUE TITLE
After succesfull login, inside the wishlist page the buttons designing are coming different they have to be same.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#36]
**Actual result:**
After successfull login, inside the wishlist page the buttons designing are coming different they have to be same.
![image](https://user-images.githubusercontent.com/102131636/170201143-7758d6c2-2da6-46fc-ab51-aa040b2b8759.png)

**Expected result:**
The buttons design have to be same

**Comment by devSuneel** [comment]
not possible coming from the app

**Comment by sudhanshu0603** [comment]
ok,
