### ISSUE TITLE
When we double clicking on the screen then the error message is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#4]
**Actual result:**
When we double clicking on the screen then the error message is coming.
![image](https://user-images.githubusercontent.com/102131636/170028333-ef9f421a-50f9-4679-b881-7bc5e785fe34.png)

**Expected result:**
The error message content is protected is coming it can be removed

**Comment by ui-neelu** [comment]
It's not an issues. it's done by the client.

**Comment by sudhanshu0603** [comment]
ok
