### ISSUE TITLE
For the mobile view, the text is also of black colour it can be improved.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#40]
**Actual result:**
The text colour for this banner is same it is overlapping with each other.
![image](https://user-images.githubusercontent.com/102131636/170207209-bc7976b3-3d8e-4e75-a438-23904c422c12.png)

**Expected result:**
For the mobile view, the text is also of black colour it can be improved.

**Comment by ui-neelu** [comment]
we can't do any thing, the text is coming with banner.
