### ISSUE TITLE
In privacy policy, all the content which is not required we can removed it which are coming in uppercase inside the privacy policy page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#41]
**The url :**
https://www.studio1995co.com/pages/privacy-policy
**Actual result:**
In privacy policy, all the content which is not required we can removed it which are coming in uppercase inside the privacy policy page.
![image](https://user-images.githubusercontent.com/102131636/170208717-c87e6016-8f62-4b2b-b641-853f9e74fdc5.png)

**Expected result:**
The uppercase content can be removed which are not required.

**Comment by devSuneel** [comment]
content coming from pages, have to update it manually

**Comment by sudhanshu0603** [comment]
ok,
