### ISSUE TITLE
The content needed for this section

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#51]
**Actual result:**
The content needed for this section
![image](https://user-images.githubusercontent.com/102131636/170661500-3362060f-8ef5-4665-8e2c-4bfef2229aa9.png)

**Expected result:**
The content must be updated.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
