### ISSUE TITLE
In search page, when we are clicking on the out of stock filter in search page then the in stock products are also coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#8]
**Actual result:**
When we are clicking on the out of stock then there should not be in stock product but IN stock products are also coming.
![image](https://user-images.githubusercontent.com/102131636/170033910-1c8845e7-94b5-4082-bda0-f0a3ea54c9a1.png)
**The video issue:**
https://www.awesomescreenshot.com/video/9067293?key=9611b0f691f9998d16dee82b958a232f
**Expected result:**
When we click on the out of stock then only out of stock products have to come only.

**Comment by devSuneel** [comment]
resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
