### ISSUE TITLE
When we are clicking on the currency converter in the footer then the for the flag india the Auto location is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Nur---Internal-Store-Redesign---30-May#9]
**Actual result:**
When we are clicking on the currency converter in the footer then the for the flag india the Auto location is coming.
![image](https://user-images.githubusercontent.com/102131636/170035266-486a4829-5681-4a19-9e87-9f5d47ee3474.png)

**Expected result:**
The text auto location for the flag india is coming but the text india have to come

**Comment by devSuneel** [comment]
not an issue

**Comment by sudhanshu0603** [comment]
ok
